[package]
name = "hoplite_verbs_rs"
version = "0.1.0"
authors = ["jeremymarch <jmarch@gradcenter.cuny.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustunicodetests = { path = "../rustunicodetests" }
unicode-normalization = { version = "0.1.19", default-features = false }
itertools = "0.10.3"

[lib]
doctest = false # don't run Doc-tests for now

[profile.release.package."*"] # +
opt-level = "z" # +
debug = false
