[package]
name = "hoplite_verbs_rs"
version = "0.1.0"
authors = ["jeremymarch <jmarch@gradcenter.cuny.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustunicodetests = { path = "../rustunicodetests" }

[profile.release.package."*"] # +
opt-level = "z" # +
debug = false